apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-notes.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "my-notes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      {{- include "my-notes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            {{- range $key, $val := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
#          livenessProbe:
#            httpGet:
#              path: /api/v1/health
#              port: {{ .Values.backend.port }}
#            initialDelaySeconds: 30
#          readinessProbe:
#            httpGet:
#              path: /api/v1/health
#              port: {{ .Values.backend.port }}
#            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-notes.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP