apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-notes.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-notes.labels" . | nindent 4 }}
    app: backend
spec:
  selector:
    {{- include "my-notes.selectorLabels" . | nindent 4 }}
    app: backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8000
  type: {{ .Values.service.backend.type }}