apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-notes.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-notes.labels" . | nindent 4 }}
    app: frontend
spec:
  selector:
    {{- include "my-notes.selectorLabels" . | nindent 4 }}
    app: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 3000
  type: {{ .Values.service.frontend.type }}