apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-notes.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    {{- include "my-notes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      {{- include "my-notes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
          - name: REACT_APP_API_URL
            value: {{ .Values.frontend.env.REACT_APP_API_URL | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-notes.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}
  type: {{ .Values.frontend.service.type }}