apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-notes.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-notes.labels" . | nindent 4 }}
    app: postgres
spec:
  selector:
    {{- include "my-notes.selectorLabels" . | nindent 4 }}
    app: postgres
  ports:
    - port: {{ .Values.service.postgres.port }}
      targetPort: 5432
  type: {{ .Values.service.postgres.type }}