apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-notes.name" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}