namespace: my-notes-prod

imagePullSecrets:
  - name: ghcr-auth

backend:
  replicas: 3
  env:
    ENVIRONMENT: "production"
    SECRET_KEY: "dev-secret-key"
    LOG_LEVEL: "INFO"
    ACCESS_TOKEN_EXPIRE_MINUTES: "60"

frontend:
  replicas: 2
  service:
    type: ClusterIP

postgres:
  storage: 10Gi

ingress:
  enabled: true
  className: traefik
  host: prod.my-notes.lan
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure # используем порт 443
    cert-manager.io/cluster-issuer: "selfsigned" # или "letsencrypt-prod"
  tls:
    enabled: true
    secretName: prod-tls
