namespace: my-notes-dev

backend:
  image:
    repository: ghcr.io/dovgdanil/mynotes/mynotes-backend
    tag: dev-caf26a7
    pullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  env:
    DATABASE_URL: "postgresql://user:pass@postgres:5432/notes"
    SECRET_KEY: "dev-secret-key"
    ALGORITHM: "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: "30"
    ENVIRONMENT: "dev"
    LOG_LEVEL: "DEBUG"

frontend:
  image:
    repository: ghcr.io/dovgdanil/mynotes/mynotes-frontend
    tag: dev-caf26a7
    pullPolicy: Always #IfNotPresent
  replicas: 1
  env:
    REACT_APP_API_URL: "http://my-notes-my-notes-backend:8000/api/v1"
  port: 80
  service:
    type: ClusterIP
    port: 80

postgres:
  image: postgres:15
  replicas: 1
  port: 5432
  storage: 1Gi
  storageClass: "local-path"
  env:
    POSTGRES_USER: "user"
    POSTGRES_PASSWORD: "pass"
    POSTGRES_DB: "notes"

imagePullSecrets:
  - name: ghcr-auth

ingress:
  enabled: true
  className: traefik
  host: dev.my-notes.lan
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  tls:
    enabled: false
    secretName: dev-tls
