{{ - if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-notes.fullname" .}}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{.Values.ingress.className}}
  rules:
    - host: {{.Values.ingress.host}} # или просто используйте IP
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{include "my-notes.fullname" .}}-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{include "my-notes.fullname" .}}-backend 
                port:
                  number: {{ .Values.frontend.service.port }}
 {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
