apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: my-notes-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZG92Z2RhbmlsIiwicGFzc3dvcmQiOiJnaHBfNXVXZ3VQRUdQNHl6S1JRNkdaWXNTZ2RGSUttQ2R3NFhSNUtqIiwiYXV0aCI6IlpHOTJaMlJoYm1sc09tZG9jRjgxZFZkbmRWQkZSMUEwZVhwTFVsRTJSMXBaYzFOblpFWkpTMjFEWkhjMFdGSTFTMm89In19fQ==