namespace: my-notes-prod

backend:
  replicas: 3
  env:
    ENVIRONMENT: "production"
    SECRET_KEY: "dev-secret-key"
    LOG_LEVEL: "INFO"
    ACCESS_TOKEN_EXPIRE_MINUTES: "60"

frontend:
  replicas: 2
  service:
    type: LoadBalancer

postgres:
  storage: 10Gi

imagePullSecrets:
  - name: ghcr-auth
