apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-notes-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dovgdanil/MyNotes.git
    targetRevision: main
    path: ./helm/my-notes
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-notes-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
